whyphi/portal

- components/Form.tsx
- package-lock.json
- package.json
- tailwind.config.ts
- Implemented file upload functionality
- Clicking submit console logs state of form
- Added essay prompts
- Refactored code for reusability purposes
- Added custom style to checkbox
> feat: Implement File Upload + Manual Essay Prompt

- app/admin/create/layout.tsx
- app/admin/layout.tsx
- app/admin/listing/layout.tsx
- app/admin/page.tsx
- components/admin/ListingCard.tsx
- components/admin/NavSidebar.tsx
- components/admin/Navbar.tsx
- components/admin/Sidebar.tsx
- tailwind.config.ts
- Implement loader in admin listings homepage
- Refactored Sidebar and Navbar into SideNavbar component and also allowed sidebar to prop when screen is small
- Edited ListingCard Grid so text won't break during responsive screen size change
> refactor: Admin Homepage

- app/public/[id]/page.tsx
> chore: remove SWR import

- app/admin/layout.tsx
- app/admin/page.tsx
- app/api/auth/[...nextauth]/route.ts
- app/authError/page.tsx
- app/layout.tsx
- components/AdminLoader.tsx
- components/admin/NavSidebar.tsx
- package-lock.json
- package.json
- Implements Authentication using `next-auth` with a Google Provider
- Implement user dropdown
- Refactored layout (abstracted the flow) to ensure that all admin routes are protected from client side
- Connected vault validation by using `signIn` callback
- Create custom auth error page
`npm run dev`
> feat: Implement Authentication on Admin Routes

- app/admin/page.tsx
- components/Form.tsx
- components/admin/ListingCard.tsx
- Uses Toggle component from flowbite and updates the visibility state of each listing
- Changed style and position of visibility indicator
- State and value of `visibility` doesn't get updated if an error occurs
Manual testing; see GIF below
> feat: Implement Visibility Toggle on ListingCard

- app/admin/layout.tsx
- app/admin/settings/[listingId]/layout.tsx
- app/admin/settings/[listingId]/page.tsx
- components/admin/ListingCard.tsx
- components/admin/settings/CustomAlert.tsx
- types/listing.ts
- Creates a settings icon that links to each listing's settings page, allowing updates/changes or deletes to be made on existing listing
> feat: Create Settings Page for Listing

- components/Form.tsx
- Implemented file validation for resume and image upload (only accepts PDF, JPG, JPEG and PNG)
- Implemented button loader when form is being submitted
- Implemented input disabler when form is being submitted
> feat: Form submission refactoring

- app/public/[id]/page.tsx
- Implemented deadline validation on the client-side
- Implemented visibility validation on the client-side
- If validations fail, it routes to `/error`
Manual testing with different params on listings.
> feat: Implement Validators for Public Listings

- app/admin/broadcast/page.tsx
- app/public/sent/page.tsx
- components/EmailForm.tsx
Adds capability for signed-in users to send email blasts from the application to chapter members and/or pledges and/or others.
- Sent email to non-verified user
> feat: Display Mass Announcement Feature

- app/admin/create/page.tsx
- app/admin/listing/[listingId]/[applicantId]/page.tsx
- app/public/[id]/page.tsx
- components/Form.tsx
- types/applicant.ts
- types/form.ts
- Implemented Checkbox on Form Creation allowing user to choose if they want to collect Events Attended data
- Included `includeEventsAttended` attribute on formData
```
const initialValues: FormData = {
title: "",
questions: [],
deadline: new Date(),
includeEventsAttended: false
};
```
-
> feat: Provide Option to Collect Events Attended Data on Form

- components/Form.tsx
- types/form.ts
> refactor: Change Event Attributes to Match Spring 2024 Rush Events

- app/admin/page.tsx
- Fetching listings take time --> added loader to reflect fetch time
> refactor: Implement Loader for Fetching Listings

- app/admin/members/layout.tsx
- app/admin/members/page.tsx
- components/admin/NavSidebar.tsx
- types/admin/members.ts
> feat: Create Members Page

- components/admin/ListingCard.tsx
- types/applicant.ts
- Fixed hyperlink issue with ListingCard by using <Link> component from NextJS.
- Refactored style of ListingCard
> fix: Fixed Hyperlink Issue with ListingCard

- app/admin/create/page.tsx
- app/admin/listing/[listingId]/[applicantId]/page.tsx
- app/admin/listing/[listingId]/insights/page.tsx
- app/admin/listing/[listingId]/page.tsx
- app/admin/members/layout.tsx
- app/admin/members/page.tsx
- app/admin/page.tsx
- app/public/[id]/page.tsx
- components/Form.tsx
- components/admin/ListingCard.tsx
- components/admin/NavSidebar.tsx
- components/admin/listing/ApplicantInfoCard.tsx
- package-lock.json
- package.json
- types/admin/members.ts
- types/applicant.ts
- types/form.ts
- types/insights.ts
- Merges `v0.2 beta` (public-related features that can be pushed to production) to staging
> merge: `v0.2 beta` to `staging`

- app/admin/listing/[listingId]/insights/page.tsx
- components/admin/ListingCard.tsx
- components/admin/listing/ApplicantCard.tsx
- components/admin/listing/insights/SummaryCard.tsx
- types/insights.ts
> feat: Data Analytics – Implement Summary Cards

- app/admin/listing/[listingId]/[applicantId]/page.tsx
- app/admin/listing/[listingId]/insights/page.tsx
- app/admin/listing/[listingId]/page.tsx
- components/Form.tsx
- types/form.ts
Refactored applicant Form.tsx to ensure valid inputs that will integrate more easily with data-analytics. Specifically, the `gpa` field is now required to be a floating point number between 0 and 4. Also added a `gradMonth` field that is separate from `gradYear` (which now must be an integer).
Performed the following tests on the frontend
1. Submit form with `n/a` gpa
2. Submit form with valid numeric gpa
3. Attempt to submit form without valid numeric gpa (fails -> good)
4. Submit form with valid month/year
> feat: Form GPA and Graduation Year Validation

- components/admin/ListingCard.tsx
> refactor: Removed redundant flex css

- app/admin/create/page.tsx
- app/admin/listing/[listingId]/[applicantId]/page.tsx
- app/admin/listing/[listingId]/insights/page.tsx
- app/admin/listing/[listingId]/page.tsx
- app/admin/members/layout.tsx
- app/admin/members/page.tsx
- app/admin/page.tsx
- app/public/[id]/page.tsx
- components/Form.tsx
- components/admin/ListingCard.tsx
- components/admin/NavSidebar.tsx
- components/admin/listing/ApplicantCard.tsx
- components/admin/listing/ApplicantInfoCard.tsx
- components/admin/listing/insights/SummaryCard.tsx
- package-lock.json
- package.json
- types/admin/members.ts
- types/applicant.ts
- types/form.ts
- types/insights.ts
- Merges staging to main for chapter demo
> merge: `staging` to `main`

- app/page.tsx
- Redirects `localhost:3000/` or `why-phi.com/` to `bupct.com`
Local
Not necessary.
> refactor: Redirect Main Index to PCT Homepage

- .github/workflows/build.yml
- Implement CI for Build to prevent errors being pushed to deployment on staging and production
> feat: Add build workflow

- app/admin/create/page.tsx
- app/admin/create/preview/listing/page.tsx
> merge: staging to main

- .github/workflows/build.yml
> merge: bug fix patch on card styling

- components/admin/listing/ApplicantCard.tsx
> fix: Fixed aspect ratio of images

- components/admin/listing/ApplicantCard.tsx
Fixed aspect ratio by adding `object-cover` to `<Image>` css.
> Fixed aspect ratio

- components/admin/listing/ApplicantCard.tsx
Fixed applicant image height issue
> Merging changes from Dev/v0.2 to Staging

- components/Form.tsx
- Handles custom server-side errors (deadlines, etc) to show for a listing
Local
> feat: Implement Custom Exception Checker for Errors

- app/admin/listing/[listingId]/insights/page.tsx
Added lowercase bug fix in case rushees input incorrect casing for major/minor. This applies only to the `insights` feature and automatically all lowercases major/minor on applicants load.
Created new users with mixed case majors/minors...
> fix: added map function to ensure all majors/minors are lowercase

- components/Form.tsx
- shows error alert popup with message generated from server-side
local with deadline passed
> refactor: Implement Alert Popup for Errors (for deadline passed)

- app/admin/listing/[listingId]/insights/page.tsx
- components/Form.tsx
- components/admin/listing/ApplicantCard.tsx
> merge: v0.2 to staging

- app/admin/listing/[listingId]/insights/page.tsx
There was an issue with displaying website links in the Insights page. This PR will fix this.
> Fixed insights link

- app/api/auth/[...nextauth]/route.ts
- User's information gets deconstructed into JWT, to be used for client + server side purposes
> feat: User Info Deconstruction on JWT

- app/admin/listing/[listingId]/[applicantId]/page.tsx
- app/admin/listing/[listingId]/insights/page.tsx
- app/admin/listing/[listingId]/page.tsx
- app/admin/onboarding/layout.tsx
- app/admin/onboarding/page.tsx
- app/api/auth/[...nextauth]/route.ts
- app/contexts/AuthContext.tsx
- package-lock.json
- package.json
- styles/TextStyles.tsx
- Updated `flowbite-react` to new version to incorporate updated components
- Refactored outdated flowbite components to new version
- Created an onboarding page for users to add necessary information regarding account
- Setup an update trigger for new sessions after onboarding in `app/api/auth/[...nextauth]/route.ts`
See video recording below.
https://github.com/whyphi/portal/assets/44107246/b2472aa3-17d0-4ebf-8923-bb831a8218e2
> feat: Create Onboarding for New Users

- app/admin/qr/layout.tsx
- app/admin/qr/page.tsx
- components/admin/NavSidebar.tsx
- Implements QR Code tab so users can quickly access their personal QR-code
> feat: Implement Personal QR Code Sidebar

- app/admin/events/[eventId]/attendance/page.tsx
- app/admin/events/[eventId]/checkin/page.tsx
- app/admin/events/[eventId]/page.tsx
- app/admin/events/layout.tsx
- app/admin/events/page.tsx
- components/admin/NavSidebar.tsx
- components/admin/events/CreateTimeframe.tsx
- components/admin/events/EventsList.tsx
- package-lock.json
- package.json
- types/admin/events.ts
- utils/date.ts
- Creates Events Page to handle the following features:
- manages events for a specific timeframe/semester
- allows user to create events in timeframe
- basic UI for CRUD on events
- QR-code check-in feature for each event
See below
https://github.com/whyphi/portal/assets/44107246/e5968c26-748d-4fed-a1cb-c4800984b06e
> feat: Create Events Page

- app/admin/events/[eventId]/checkin/page.tsx
> chore: change camera setting to environment

- app/admin/accountability/page.tsx
- package-lock.json
- package.json
- Implemented Accountability Table using ag-grid
> feat: Implement Accountability Table

- app/page.tsx
- components/admin/NavSidebar.tsx
> feat: Implement Login Homepage

- components/admin/NavSidebar.tsx
> merge: continuation of v1.0b

- app/admin/rush/layout.tsx
- app/admin/rush/page.tsx
- app/page.tsx
- components/admin/NavSidebar.tsx
- components/admin/rush/CreateDrawer.tsx
- types/admin/events.ts
> feat: Rush Events Management

- app/contexts/AuthContext.tsx
- hotfix on providing onboarding when users do not have `isNewUser` field
> refactor: Handle isNewUser empty field for Onboarding

- app/admin/events/[eventId]/checkin/page.tsx
- app/admin/qr/page.tsx
> refactor: QR-Code

- app/contexts/AuthContext.tsx
> hotfix: fix infinite reloading

- app/contexts/AuthContext.tsx
> hotfix: fix infinite reload on onboarding

- app/admin/onboarding/page.tsx
- app/contexts/AuthContext.tsx
> refactor: style + add major/minor fields

- app/contexts/AuthContext.tsx
> hotfix: another validator

- app/admin/rush/page.tsx
- Disabled button when no inputs were provided
- Checks for whitespaces before making an API call
Local, see below.
https://github.com/whyphi/portal/assets/44107246/3fc5afbb-10f9-4a14-a4f2-24e948d5026a
> fix: Implement Rush Event Validation on Client-side

- app/admin/rush/page.tsx
- types/admin/events.ts
- Created a button that allows users to see the code based on a toggle
Local
https://github.com/whyphi/portal/assets/44107246/b59e7a69-e52f-4740-a606-7c4d07a6c3c3
> feat: Implement Code Toggle for Rush Events

- app/admin/rush/page.tsx
- Delete rush event functionality
Delete
https://github.com/whyphi/portal/assets/44107246/4ae29484-8cb5-4b33-91af-9c82991b9325
> feat: Implement CRUD Components for Rush Event Management

- app/admin/rush/page.tsx
- types/admin/events.ts
> merge: v1.0.6

- app/PostHogPageView.tsx
- app/layout.tsx
- app/providers/index.tsx
- package-lock.json
- package.json
> feat: Implement Posthog Web Analytics

- app/admin/listing/[listingId]/page.tsx
- components/admin/listing/ApplicantCard.tsx
- utils/delay.ts
This PR aims to make the UI more intuitive when clicking "back" after viewing an applicant by highlighting the previously clicked applicant when scrolling to them.
I also added a `delay(ms)` function that makes it easier to write async/await code (similar to time.sleep in other languages)
> added functionality to change color briefly when scrolling to applicant

- app/admin/listing/[listingId]/insights/page.tsx
- components/admin/listing/ApplicantCard.tsx
Fixed navigation links for the `insights` page to route to `admin/listing/${params.listingId}` rather than `admin/listing/${params.listingId}/${params.applicantId}`. These changes were necessary to prevent errors after the previous PR to optimize applicant iteration.
> fixed router push when clicking on table row of insights

- .github/release.yml
- Created yaml script to utilize tag-based release description automation to keep track of new updates per release.
> feat: Implement GitHub Release Automation

- app/admin/rush/[eventId]/page.tsx
- app/admin/rush/page.tsx
- components/admin/rush/CreateDrawer.tsx
- components/admin/rush/Image/CropImage.tsx
- types/admin/events.ts
Mainly just added some UI features via Flowbite as well as improved mobile accessibility. Also cleaned up some dead code.
> Fix/rush events UI polish

- app/admin/account-settings/layout.tsx
- app/admin/account-settings/page.tsx
- app/contexts/AuthContext.tsx
- components/admin/NavSidebar.tsx
- types/admin/account-settings/member.ts
- Created account settings page where users are able to update details about themselves (to be utilized for family tree feature)
> feat: create update account settings page

- app/admin/settings/[listingId]/page.tsx
Fixed authorization error preventing `Listings` from being updated/deleted.
> fixed authorization bugs

- app/admin/events/page.tsx
- app/admin/family-tree/layout.tsx
- app/admin/family-tree/page.tsx
- app/admin/rush/page.tsx
- components/admin/NavSidebar.tsx
- components/admin/events/EventsList.tsx
- components/admin/events/settings/TimeframesList.tsx
- package-lock.json
- package.json
Adjusted `Member Events` UI to be more consistent with `Rush Events`.
https://github.com/user-attachments/assets/dd4f0d27-3c2b-4f84-bbd5-d70cdb524218
> Fix/member events UI

- app/admin/rush/[categoryId]/analytics/page.tsx
> fixed endpoint

- utils/getBaseURL.ts
Hopefully should resolve errors when navigating to rush event link.
> adjusted end of base url

- app/admin/rush/page.tsx
- components/admin/rush/EventModal.tsx
- components/admin/rush/Image/CropImage.tsx
- components/admin/rush/Image/ImagePlaceholder.tsx
- types/admin/events.ts
- utils/getBaseURL.ts
Fixed some notable bugs to prevent image caching when `eventCoverImage` is changed. Also added image loading skeleton...
> Merge: `2.0.1`

- app/admin/account-settings/page.tsx
- app/admin/create/page.tsx
- app/admin/create/preview/listing/page.tsx
- app/admin/events/[eventId]/attendance/page.tsx
- app/admin/onboarding/page.tsx
- app/contexts/AuthContext.tsx
- app/public/[id]/page.tsx
- components/Form.tsx
- components/admin/NavSidebar.tsx
- components/admin/listing/ApplicantPage.tsx
- types/admin/events.ts
- types/form.ts
> Revert "Merge: `v2.0.2`"

- app/admin/account-settings/page.tsx
- app/admin/create/page.tsx
- app/admin/create/preview/listing/page.tsx
- app/admin/events/[eventId]/attendance/page.tsx
- app/admin/onboarding/page.tsx
- app/contexts/AuthContext.tsx
- app/public/[id]/page.tsx
- components/Form.tsx
- components/admin/NavSidebar.tsx
- components/admin/listing/ApplicantPage.tsx
- types/admin/events.ts
- types/form.ts
Link `listing` to `rush-category`
> Merge: `v2.0.2`

- components/Form.tsx
Removed `RenderEventsAttendedSection` in `Form.tsx`
> Removed `RenderEventsAttendedSection` in `Form.tsx`

- components/Form.tsx
> removed RenderEventsAttended (fixed Release: `2.0.2`)

- app/admin/rush/[categoryId]/analytics/page.tsx
- components/admin/listing/ApplicantInfoCard.tsx
- types/admin/events.ts
- utils/getRushThreshold.ts
Added bug fixes:
1. Adds logic to decide if rush has attended the appropriate number of events for an interview
2. Fixed bug when opening URLs that are not prefixed by "http" or "https"
> Release: `3.0.1`

- components/admin/listing/ApplicantInfoCard.tsx
Forgot to also fix the URL opening for websites (not just linkedin), fixed now)
> Merge: `3.0.2`

- components/admin/listing/ApplicantInfoCard.tsx
Re-attempting to fix website URL opening (scuffed up the last PR 😅)
> release: `3.0.3`

- app/admin/rush/[categoryId]/analytics/page.tsx
- utils/admin/rush/analytics.ts
- Created overview cards, giving general analytics of rush
Local
> feat: Create Rush Analytics Overview Card

- app/admin/rush/[categoryId]/analytics/page.tsx
- utils/admin/rush/analytics.ts
- Utilized `recharts` to show rush events count
Local
> feat: Implement Bar Chart for Rush Events Count

- app/api/auth/[...nextauth]/route.ts
> fix: Use proper role assignments in token session

- app/admin/create/page.tsx
- app/admin/listing/[listingId]/insights/page.tsx
- app/admin/listing/[listingId]/page.tsx
- app/admin/page.tsx
- app/admin/settings/[listingId]/page.tsx
- app/api/auth/[...nextauth]/route.ts
- app/public/[id]/page.tsx
- components/Form.tsx
- components/admin/listing/ApplicantCard.tsx
- components/admin/listing/ApplicantInfoCard.tsx
- components/admin/listing/ApplicantPage.tsx
- types/applicant.ts
- types/form.ts
- types/listing.ts
> dev/v3.1 release (supabase migration)

- app/admin/create/page.tsx
- app/admin/listing/[listingId]/insights/page.tsx
- app/admin/listing/[listingId]/page.tsx
- app/admin/page.tsx
- app/admin/settings/[listingId]/page.tsx
- app/api/auth/[...nextauth]/route.ts
- app/public/[id]/page.tsx
- components/Form.tsx
- components/admin/listing/ApplicantCard.tsx
- components/admin/listing/ApplicantInfoCard.tsx
- components/admin/listing/ApplicantPage.tsx
- types/applicant.ts
- types/form.ts
- types/listing.ts
> 3.1 release (supabase migration)
